[package]
name = "Note"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
pulldown-cmark = "0.9.3"
rand = "0.9.0"
regex = "1.11.1"
thiserror = "2.0.11"
